image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 22  

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - command: code-server --user-data-dir data --auth none
  # mongoimport --host cluster0-shard-00-02.aba5z.mongodb.net:27017 --db student --collection grade --type csv --file grades.csv --headerline --authenticationDatabase admin --ssl --username dbUser --password dbUserPass
  - command: mongo "mongodb+srv://cluster0.aba5z.mongodb.net/student" --username dbUser --password dbUserPass
  - command: sdk install -y java 20.0.0.r11-grl
  #- command: sdk d java 20.0.0.r11-grl
  - command: sdk install -y scala 2.12.12
  - command: sdk install -y spark 2.4.6
  - command: sdk install -y sbt 1.3.9
  
  

vscode:
  extensions:
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
    - esbenp.prettier-vscode@5.1.3:t532ajsImUSrA9N8Bd7jQw==
    - msjsdiag.debugger-for-chrome@4.12.6:IdQBlCQEnixzHAOkHC36ew==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - humao.rest-client@0.24.1:ggeyvIVSWsjotnh1tr2HMw==
    - WallabyJs.quokka-vscode@1.0.312:Tm1xSg4Ny48Gd8AHf1SJNg==
    - mongodb.mongodb-vscode@0.1.1:YxL4c1szW0z9jpy6o32YLg==
    - leizongmin.node-module-intellisense@1.5.0:l5gZ4eB82kEQ+FF7GzPJew==
    - dsznajder.es7-react-js-snippets@2.8.3:MZFzngN6QMMcVWw8QkIFOQ==
    - redhat.vscode-quarkus@1.6.0:L1WGCvkSZeXbqk0esLq6mQ==
    - scala-lang.scala@0.4.3:4toR7IuVtVqB/cqkVaTgZg==
    - scalameta.metals@1.9.3:Ul5QiWDI6XaZcygyT9BSCg==
