image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  #- port: 22 
  #- port: 2222
  #- port: 4000 

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - command: code-server --user-data-dir data --auth none
  # - command: code-server --extensions-dir /home/gitpod/.gitpod-code/extensions --auth none
  # mongoimport --host cluster0-shard-00-02.aba5z.mongodb.net:27017 --db student --collection grade --type csv --file grades.csv --headerline --authenticationDatabase admin --ssl --username dbUser --password dbUserPass
  - command: mongo "mongodb+srv://cluster0.aba5z.mongodb.net/student" --username dbUser --password dbUserPass
  - command: sdk install -y java 20.0.0.r11-grl
#- command: sdk d java 20.0.0.r11-grl
  - command: sdk install -y scala 2.12.12
  - command: sdk install -y spark 2.4.6
  - command: sdk install -y sbt 1.3.9
  - command: cd ~ && rm -r .gitpod-code && ln -s /workspace/Workspace-VSCode-GitPod/.gitpod-config .gitpod-code
  
  




