pull_request_rules:
  - name: CI passes and is @types package from dependabot
    conditions:
      - "#status-success>=3"
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=^Bump @types/(\w+) from .*$
      - base=master
    actions:
      merge:
        method: merge
